title: Jindrich Consulting LLC
email: jindrich.consulting.llc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
domain: "jindrich-consulting-llc.github.io"
url: "https://jindrich-consulting-llc.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Site globals
company:
  name: "Jindrich Consulting LLC"
  email: "jindrich.consulting.llc@gmail.com"
  address: "522 W RIVERSIDE AVE # 8571 Spokane, WA 99201"