- name: "Data Analytics"
  url: "/services/data-analytics"
  description: "Analyzes performance, customer satisfaction, and historical data, enabling businesses to make informed decisions, optimize strategies, and drive growth."
- name: "Data Engineering"
  url: "/services/data-engineering"
  description: "Building systems to collect, store, and process data, ensuring its quality and availability for analysis."
