- name: "Data Analytics"
  description: "Analyze performance and customer data to help businesses optimize strategies and drive growth."
  url: "/services/data-analytics"
  icon: "../assets/img/icons/icons8-bar-chart-96.png"
  image: "../assets/img/cards/Gemini_Generated_Image_Dashboard.jpeg"
- name: "Data Engineering"
  description: "Build systems to collect, store, and process data for analysis, ensuring quality and availability."
  url: "/services/data-engineering"
  icon: "../assets/img/icons/icons8-database-administrator-96.png"
  image: "../assets/img/cards/Gemini_Generated_Image_Computer_Screen.jpeg"
